language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
  - yarn run deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
    env:
global:
  - secure: "PJYLBEJF8CVxomCSoYxD/tu4pMuaxSpkmpO61411R/iCLRnTSzMxfkTe2gFgplt55b9IJpYwzbaxpG87q00mr8eCJLjdHLnJTpo8tupJI3gnZrCi1Fk1k+sAfsa+p814Kkt9jgv0LHYh+KsbPN7rC4yhcbBxbMUqJZGZM3RlJPz++zJTR3HLrLYvUuxE/lREYs0pW/VVEdzfFsb5pQ76O8qYnrlNJb4nU0Dc/OUIufKeDlK4VxtuyLa8KxjrhowFbYBPu8aeyd8pRGAX/RHPaxbPL5yYoxXgEySr4dwus+nZ8hAficjTqAC/b6pnVeDdPK+Ks/42FKFkTBe8plXdDY4pPjQ87JnEey6t0l106Q/rJ4rOe2uqYFQDoxnIn1v/B8qbhnw0do0XFJ5q5gv5mZAu0lZxVkH+O/obprPhIa8APeZIZ8BZlTpF2H0Vc7HdqJMSezORSjT72Cao7pUodw1L5jAXevaZQ3/OSng7dbJ92nPE6fXbUSVHvLWjNAQbSiJRi7vmvU3Aq56iXaAnmG5Qz2LkI3AoceE5OkfUQQtuyjFth47y955aCCDGJIo6x2TK5OuijojqhJiuawpUZh0juYDDOJQpvi31B5rmp73Tzs39Ca85deVqqy0nC27YmS4eHA2NkmgDcZWOXWv8htcy4XwX5chfOKaVDxWkpjM="
